### ISSUE TITLE
Builds issues on linux 3.16.0

### ISSUE THREAD

**Issue by lesniewski** [plasma-umass/coz#16]
Hi folks, interesting project. I wanted to try coz out on a profiling task, but I haven't been able to get it to build. I'm using the latest clang and libc++ pulled from trunk, and the headers from the ubuntu package linux-headers-3.16.0-33{,-generic}. Unfortunately, the `hw_breakpoint.h` and `perf_event.h` header files are aggressively C++-hostile:

```
$ /opt/llvm/bin/clang++ --std=c++11 -g -O2 -fPIC -I../include -I../deps -I../deps -I/usr/src/linux-headers-3.16.0-33/arch/x86/include -I/usr/src/linux-headers-3.16.0-33/include -g -O2 -stdlib=libc++ -MMD -MP -o obj/perf.o -c perf.cpp
In file included from perf.cpp:1:
In file included from ./perf.h:4:
In file included from /usr/src/linux-headers-3.16.0-33/include/linux/hw_breakpoint.h:4:
In file included from /usr/src/linux-headers-3.16.0-33/include/linux/perf_event.h:17:
In file included from /usr/src/linux-headers-3.16.0-33/include/uapi/linux/perf_event.h:17:
In file included from /usr/src/linux-headers-3.16.0-33/include/linux/types.h:5:
In file included from /usr/src/linux-headers-3.16.0-33/include/uapi/linux/types.h:13:
In file included from /usr/include/linux/posix_types.h:4:
/usr/src/linux-headers-3.16.0-33/include/linux/stddef.h:11:2: error: expected identifier
        false   = 0,
        ^
/usr/src/linux-headers-3.16.0-33/include/linux/stddef.h:12:2: error: expected identifier
        true    = 1
        ^
In file included from perf.cpp:1:
In file included from ./perf.h:4:
In file included from /usr/src/linux-headers-3.16.0-33/include/linux/hw_breakpoint.h:4:
In file included from /usr/src/linux-headers-3.16.0-33/include/linux/perf_event.h:17:
In file included from /usr/src/linux-headers-3.16.0-33/include/uapi/linux/perf_event.h:17:
/usr/src/linux-headers-3.16.0-33/include/linux/types.h:29:9: error: unknown type name '_Bool'
typedef _Bool                   bool;
        ^
/usr/src/linux-headers-3.16.0-33/include/linux/types.h:29:17: error: expected unqualified-id
typedef _Bool                   bool;
                                ^
In file included from perf.cpp:1:
In file included from ./perf.h:4:
In file included from /usr/src/linux-headers-3.16.0-33/include/linux/hw_breakpoint.h:4:
In file included from /usr/src/linux-headers-3.16.0-33/include/linux/perf_event.h:38:
/usr/src/linux-headers-3.16.0-33/include/linux/list.h:37:49: error: expected ')'
static inline void __list_add(struct list_head *new,
                                                ^
/usr/src/linux-headers-3.16.0-33/include/linux/list.h:37:30: note: to match this '('
static inline void __list_add(struct list_head *new,
                             ^
/usr/src/linux-headers-3.16.0-33/include/linux/list.h:41:2: error: use of undeclared identifier 'next'
        next->prev = new;
        ^
/usr/src/linux-headers-3.16.0-33/include/linux/list.h:41:18: error: expected a type
        next->prev = new;
                        ^
/usr/src/linux-headers-3.16.0-33/include/linux/list.h:42:5: error: expected a type
        new->next = next;
           ^
/usr/src/linux-headers-3.16.0-33/include/linux/list.h:43:5: error: expected a type
        new->prev = prev;
           ^
/usr/src/linux-headers-3.16.0-33/include/linux/list.h:44:2: error: use of undeclared identifier 'prev'
        prev->next = new;
        ^
/usr/src/linux-headers-3.16.0-33/include/linux/list.h:44:18: error: expected a type
        prev->next = new;
                        ^
/usr/src/linux-headers-3.16.0-33/include/linux/list.h:60:47: error: expected ')'
static inline void list_add(struct list_head *new, struct list_head *head)
                                              ^
/usr/src/linux-headers-3.16.0-33/include/linux/list.h:60:28: note: to match this '('
static inline void list_add(struct list_head *new, struct list_head *head)
                           ^
/usr/src/linux-headers-3.16.0-33/include/linux/list.h:62:16: error: expected a type
        __list_add(new, head, head->next);
                      ^
/usr/src/linux-headers-3.16.0-33/include/linux/list.h:74:52: error: expected ')'
static inline void list_add_tail(struct list_head *new, struct list_head *head)
                                                   ^
/usr/src/linux-headers-3.16.0-33/include/linux/list.h:74:33: note: to match this '('
static inline void list_add_tail(struct list_head *new, struct list_head *head)
                                ^
/usr/src/linux-headers-3.16.0-33/include/linux/list.h:76:16: error: expected a type
        __list_add(new, head->prev, head);
                      ^
/usr/src/linux-headers-3.16.0-33/include/linux/list.h:107:16: error: arithmetic on a pointer to void
        entry->next = LIST_POISON1;
                      ^~~~~~~~~~~~
/usr/src/linux-headers-3.16.0-33/include/linux/poison.h:22:44: note: expanded from macro 'LIST_POISON1'
#define LIST_POISON1  ((void *) 0x00100100 + POISON_POINTER_DELTA)
                       ~~~~~~~~~~~~~~~~~~~ ^
In file included from perf.cpp:1:
In file included from ./perf.h:4:
In file included from /usr/src/linux-headers-3.16.0-33/include/linux/hw_breakpoint.h:4:
In file included from /usr/src/linux-headers-3.16.0-33/include/linux/perf_event.h:38:
/usr/src/linux-headers-3.16.0-33/include/linux/list.h:108:16: error: arithmetic on a pointer to void
        entry->prev = LIST_POISON2;
                      ^~~~~~~~~~~~
/usr/src/linux-headers-3.16.0-33/include/linux/poison.h:23:44: note: expanded from macro 'LIST_POISON2'
#define LIST_POISON2  ((void *) 0x00200200 + POISON_POINTER_DELTA)
                       ~~~~~~~~~~~~~~~~~~~ ^
In file included from perf.cpp:1:
In file included from ./perf.h:4:
In file included from /usr/src/linux-headers-3.16.0-33/include/linux/hw_breakpoint.h:4:
In file included from /usr/src/linux-headers-3.16.0-33/include/linux/perf_event.h:38:
/usr/src/linux-headers-3.16.0-33/include/linux/list.h:123:23: error: expected ')'
                                struct list_head *new)
                                                  ^
/usr/src/linux-headers-3.16.0-33/include/linux/list.h:122:32: note: to match this '('
static inline void list_replace(struct list_head *old,
                               ^
/usr/src/linux-headers-3.16.0-33/include/linux/list.h:125:5: error: expected a type
        new->next = old->next;
           ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
```

I took a stab at working around this by #defining away the keywords such as true/false/new/bool, but there are still issues with pointer incompatibilty, literal suffixes, etc. In short it seems the linux headers really aren't meant to be compiled by a C++ compiler.

Could you share the version of the linux kernel headers you have been using?

**Comment by emeryberger** [comment]
FWIW I just built this on a clean install of Ubuntu 14.04. Kernel version is 3.13.0-65-generic. I had to `cd deps/libelfin; make` but other than that, everything built and worked fine. As far as I am aware, coz does *not* need the Linux source headers to build, so something is awry.

**Comment by bpowers** [comment]
`perf.cpp` does pull in:

```
#include <linux/hw_breakpoint.h>
#include <linux/perf_event.h>
```

I've got a recent clang + llvm (`clang version 3.8.0 (git@github.com:llvm-mirror/clang.git 0461540c59362540245492dccc0883dea485554c)`) from Sept 24, and am able to successfully link against libc++.  Linux 4.2.2.

I think the weird thing above thats happening is that `/usr/include/linux/posix_types.h` is finding some stub `stddef.h` in that linux-headers package, rather than the system `stddef.h` which sure as hell should be C++-safe.  Best I can figure is this has something to do with the `-I` include paths you've got above.  I committed the changes I made to build against libc++ here:

https://github.com/bpowers/coz/commit/9fdba5a54dee4450ddaf782132d7cbc59d062a96

Hopefully this helps a little bit.

**Comment by bpowers** [comment]
Hi @lesniewski ,

Specifically, you are including the kernel-side of the linux kernel headers, those meant for building Linux kernel modules, rather than those intended to be used to access Kernel APIs from userspace.  You shouldn't need to add any extra `-I` include paths - the Ubuntu package should install a symlink to what you need into `/usr/include/linux`, which will be automatically found when we use angle-bracket includes like `#include <linux/hw_breakpoint.h>`.  Can you try removing the `-I` paths you have that point into the linux-headers package and see if that helps?

**Comment by lesniewski** [comment]
Thanks all for the quick replies. What led me astray was that in my install, there isn't any /usr/include/linux/hw_breakpoint.h:
```
% /opt/llvm/bin/clang++ --std=c++11 -g -O2 -fPIC -I../include -I../deps -I../deps -g -O2 -stdlib=libc++ -MMD -MP -o obj/perf.o -c perf.cpp
In file included from perf.cpp:1:
./perf.h:4:10: fatal error: 'linux/hw_breakpoint.h' file not found
#include <linux/hw_breakpoint.h>
```

It appears that my kernel headers are behind my kernel version:

```
% dpkg -S /usr/include/linux/perf_event.h
linux-libc-dev: /usr/include/linux/perf_event.h
% dpkg -l linux-libc-dev
...
ii  linux-libc-dev            3.2.0-84.121              Linux Kernel Headers for development
% uname -r
3.16.0-33-generic
```

Is Ubuntu precise just too old to build coz?

**Comment by bpowers** [comment]
I'm not sure, and I probably won't be able to get a precise install setup in the next few days as I will be traveling.

If `perf_event.h` is there, you might be able to just not use `hw_breakpoint.h`.

This change removes the direct use of `hw_breakpoint.h` and compiles for me:

```
diff --git a/libcoz/perf.cpp b/libcoz/perf.cpp
index 99a197c..1f1d38d 100644
--- a/libcoz/perf.cpp
+++ b/libcoz/perf.cpp
@@ -2,7 +2,6 @@
 
 #include <asm/unistd.h>
 #include <fcntl.h>
-#include <linux/hw_breakpoint.h>
 #include <linux/perf_event.h>
 #include <poll.h>
 #include <signal.h>
diff --git a/libcoz/perf.h b/libcoz/perf.h
index 1ac4433..dc2e41f 100644
--- a/libcoz/perf.h
+++ b/libcoz/perf.h
@@ -1,7 +1,7 @@
 #if !defined(CAUSAL_RUNTIME_PERF_H)
 #define CAUSAL_RUNTIME_PERF_H
 
-#include <linux/hw_breakpoint.h>
+#define HW_BREAKPOINT_X 4
 #include <linux/perf_event.h>
 #include <sys/types.h>
```

Maybe you could try that and report back @lesniewski?

**Comment by lesniewski** [comment]
Thanks for the update - seems like a step in the right direction. I pulled and rebuilt, but it seems that my version of perf_event.h is missing some enums:
```
In file included from perf.cpp:1:
./perf.h:65:20: error: use of undeclared identifier 'PERF_SAMPLE_BRANCH_STACK'
    branch_stack = PERF_SAMPLE_BRANCH_STACK,
                   ^
./perf.h:66:12: error: use of undeclared identifier 'PERF_SAMPLE_REGS_USER'; did you mean 'PERF_SAMPLE_READ'?
    regs = PERF_SAMPLE_REGS_USER,
           ^~~~~~~~~~~~~~~~~~~~~
           PERF_SAMPLE_READ
/usr/include/linux/perf_event.h:124:2: note: 'PERF_SAMPLE_READ' declared here
        PERF_SAMPLE_READ                        = 1U << 4,
        ^
In file included from perf.cpp:1:
./perf.h:67:13: error: use of undeclared identifier 'PERF_SAMPLE_STACK_USER'
    stack = PERF_SAMPLE_STACK_USER,
            ^
./perf.h:92:13: error: use of undeclared identifier 'PERF_RECORD_MMAP2'; did you mean 'PERF_RECORD_MMAP'?
    mmap2 = PERF_RECORD_MMAP2
            ^~~~~~~~~~~~~~~~~
            PERF_RECORD_MMAP
/usr/include/linux/perf_event.h:367:2: note: 'PERF_RECORD_MMAP' declared here
        PERF_RECORD_MMAP                        = 1,
        ^
4 errors generated.
make[1]: *** [obj/perf.o] Error 1
```

Here's the version of the package containing `/usr/include/linux/perf_event.h`:
```
ii  linux-libc-dev            3.2.0-84.121              Linux Kernel Headers for development
```

**Comment by ccurtsinger** [comment]
I will have to take a closer look at this in the next week or two. I may be able to resolve this with `#ifdef` guards, but there may have to be a minimum linux version.

**Comment by lesniewski** [comment]
Thank you for investigating!

**Comment by petterreinholdtsen** [comment]
The build work with linux-libc-dev version 4.6.3-1, so the missing enums were added between 3.2.0 and 4.6.3.  Is it possible to build a reduced version without these enums?
