### ISSUE TITLE
Compilation error on CentOS

### ISSUE THREAD

**Issue by gupta-suyash** [plasma-umass/coz#155]
Hello

I am trying to install coz on CentOS and have tried to closely follow all the installation instructions. However, I am getting following errors:

**Comment by Tridacnid** [comment]
`gettid` errors are likely #154 

As for not finding your headers, try setting CPLUS_INCLUDE_PATH to the root of your libelfin's include dir, it sounds like you installed it to a non-standard location.

**Comment by emeryberger** [comment]
Agreed on the diagnosis. How old is this version of CentOS? (I just am wondering whether this is really worth supporting at this point.)

**Comment by Tridacnid** [comment]
I get these errors on `CentOS Linux release 7.7.1908 (Core)`

**Comment by emeryberger** [comment]
According to Wikipedia, full updates for version 7 have already ended (though maintenance releases continue). Can you test on the latest release? (Version 8)

**Comment by Tridacnid** [comment]
I can't but I'm sure it would work; Cent8 has a much more modern toolchain. From my understanding, CentOS is more common in enterprise than consumer/regular user land, so it's really up to you how you weigh supporting it. We were able to work around it by manually reverting #154.

**Comment by julsebeng** [comment]
I was having this issue when attempting to build on CentOS 7.9.2009. My solution was simply to clone the `libelfin` project inside of the `/libcoz` folder and build it there; the file structure looking something like this: `coz/libcoz/libelfin/dwarf/...`. 

I had a lot of weird issues on CentOS 7 that I had to correct (like `LD_LIBRARY_PATH` not pointing to `/usr/lib`), but I was able to build everything successfully.
